QUIZ_CONFIG = {
    "aesthetic_style": [
        {"value": "Minimalist", "image_url": "https://wohnenimkleinformat.de/wp-content/uploads/kueche-mit-kochinsel-boho.png"},
        {"value": "Modern", "image_url": "https://i.pinimg.com/1200x/b0/0d/8b/b00d8bef45550c2ac16a11ca7915da92.jpg"},
        {"value": "Industrial", "image_url": "https://hauszi.de/wp-content/uploads/2025/05/1__Insel-Liebe__Dein_Industrial-Hub_f_r_Genuss___Gespr_ch-1.png"},
        {"value": "Maximalist", "image_url": "https://i.pinimg.com/736x/2b/41/5d/2b415d0e89cb0d75039d5af3ea34650f.jpg"},
        {"value": "Traditional", "image_url": "https://i.pinimg.com/736x/47/e0/93/47e093a147bd6c6c34813c934d2512d5.jpg"},
        {"value": "Art Deco", "image_url": "https://i.pinimg.com/736x/d8/fd/e7/d8fde767bc0870d3da26cf00a74a1edb.jpg"},
        {"value": "Cottagecore", "image_url": "https://i.pinimg.com/736x/6f/a0/5f/6fa05f94fc64226ea2d6b79ce1dfda56.jpg"},
    ],
    "mood_feel": [
        {"value": "Cosy & Inviting", "image_url": "https://i.pinimg.com/736x/1a/1e/5a/1a1e5a8116f7a16acaa2874c11bf0b03.jpg"},
        {"value": "Sleek & Modern", "image_url": "https://in.pinterest.com/pin/49821139624398467/"},
        {"value": "Serene & Calm", "image_url": "https://i.pinimg.com/1200x/4e/34/33/4e34332a13d46736f0e37721d72ef43a.jpg"},
        {"value": "Rustic & Warm", "image_url": "https://i.pinimg.com/1200x/fd/98/c2/fd98c23edcb3d1625f434a30ee5c2780.jpg"},
        {"value": "Luxurious & Opulent", "image_url": "https://i.pinimg.com/1200x/35/1c/2d/351c2d8c81f5ecfc1719c33ec26a3e01.jpg"},
        {"value": "Natural & Organic", "image_url": "https://i.pinimg.com/1200x/32/89/95/328995c858d9bd65eb88f388d052b54c.jpg"},
    ],
}

GLB_CATEGORIES = [
    {
        "id": "living-room",
        "title": "Living Room",
        "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/sofa_01.glb",
        "thumbnail_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600",
    },
    {
        "id": "bedroom",
        "title": "Bedroom",
        "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/bed_06.glb",
        "thumbnail_url": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600",
    },
    {
        "id": "kitchen",
        "title": "Kitchen",
        "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/gas_stove.glb",
        "thumbnail_url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600",
    },
    {
        "id": "decor",
        "title": "Decor",
        "glb_url": "disco_ball.glb",
        "thumbnail_url": "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600",
    },
    {
        "id": "classroom",
        "title": "Classroom",
        "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/whiteboard_low-poly.glb",
        "thumbnail_url": "https://github.com/Morningstar777-star/Images/blob/main/classroom-interior-with-school-desks-chairs-and-green-board-empty-school-classroom-photo.webp",
    },
]

PRODUCTS = [
    {
        "sku": "SOFA-001",
        "name": "Aero Modular Cloud Sofa",
        "description": "Pet-friendly modular sofa with premium fabric.",
        "category_id": "living-room",
        "price_inr": 78000,
        "stock": 10,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/sofa_01.glb",
        },
        "attributes": {
            "aesthetic_style": "Minimalist",
            "mood_feel": "Serene & Calm",
            "price_tier": "premium",
            "dominant_colors": ["white", "cream"],
            "materials": ["performance canvas", "wood"],
        },
    },
    {
        "sku": "BED-002",
        "name": "Lumiere Platform Bed",
        "description": "Low-profile walnut platform bed.",
        "category_id": "bedroom",
        "price_inr": 42000,
        "stock": 7,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/bed_06.glb",
        },
        "attributes": {
            "aesthetic_style": "Modern",
            "mood_feel": "Sleek & Modern",
            "price_tier": "premium",
            "dominant_colors": ["walnut", "black"],
            "materials": ["veneer", "steel"],
        },
    },
    {
        "sku": "RUG-003",
        "name": "Hearthline Woven Rug",
        "description": "Warm rustic woven rug for cozy spaces.",
        "category_id": "decor",
        "price_inr": 9500,
        "stock": 22,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1493666438817-866a91353ca9?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/disco_ball.glb",
        },
        "attributes": {
            "aesthetic_style": "Traditional",
            "mood_feel": "Rustic & Warm",
            "price_tier": "luxury",
            "dominant_colors": ["beige", "brown"],
            "materials": ["wool"],
        },
    },
    {
        "sku": "LAMP-004",
        "name": "Onyx Arc Floor Lamp",
        "description": "Matte black arc lamp with warm glow.",
        "category_id": "living-room",
        "price_inr": 6200,
        "stock": 18,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/disco_ball.glb",
        },
        "attributes": {
            "aesthetic_style": "Industrial",
            "mood_feel": "Sleek & Modern",
            "price_tier": "premium",
            "dominant_colors": ["black", "gold"],
            "materials": ["steel", "glass"],
        },
    },
    {
        "sku": "BED-003",
        "name": "Cosy Bed Classic",
        "description": "Comfort-first bed with plush headboard and soft contours.",
        "category_id": "bedroom",
        "price_inr": 38900,
        "stock": 9,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/cosy_bed.glb",
        },
        "attributes": {
            "aesthetic_style": "Modern",
            "mood_feel": "Cosy & Inviting",
            "price_tier": "premium",
            "dominant_colors": ["beige", "oak"],
            "materials": ["fabric", "wood"],
        },
    },
    {
        "sku": "KIT-101",
        "name": "Gas Stove Pro",
        "description": "Modern cooktop with efficient burners for everyday cooking.",
        "category_id": "kitchen",
        "price_inr": 11999,
        "stock": 15,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/gas_stove.glb",
        },
        "attributes": {
            "aesthetic_style": "Modern",
            "mood_feel": "Sleek & Modern",
            "price_tier": "premium",
            "dominant_colors": ["black", "steel"],
            "materials": ["steel", "glass"],
        },
    },
    {
        "sku": "KIT-102",
        "name": "Gas Stove KG67",
        "description": "Compact stove variant for smaller kitchen layouts.",
        "category_id": "kitchen",
        "price_inr": 10499,
        "stock": 11,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/gas_stove_kg67mtl.glb",
        },
        "attributes": {
            "aesthetic_style": "Modern",
            "mood_feel": "Serene & Calm",
            "price_tier": "medium",
            "dominant_colors": ["black", "gray"],
            "materials": ["metal", "glass"],
        },
    },
    {
        "sku": "KIT-103",
        "name": "Kitchen Accessories Set",
        "description": "Everyday kitchen accessories set for prep and serving.",
        "category_id": "kitchen",
        "price_inr": 3499,
        "stock": 20,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/kitchen_accessories_v1.glb",
        },
        "attributes": {
            "aesthetic_style": "Traditional",
            "mood_feel": "Cosy & Inviting",
            "price_tier": "medium",
            "dominant_colors": ["wood", "steel"],
            "materials": ["wood", "metal"],
        },
    },
    {
        "sku": "KIT-104",
        "name": "Low Poly Blender Red",
        "description": "Countertop blender model for modern kitchen collections.",
        "category_id": "kitchen",
        "price_inr": 2899,
        "stock": 24,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/low_poly_blender_red.glb",
        },
        "attributes": {
            "aesthetic_style": "Modern",
            "mood_feel": "Sleek & Modern",
            "price_tier": "medium",
            "dominant_colors": ["red", "white"],
            "materials": ["plastic", "steel"],
        },
    },
    {
        "sku": "KIT-105",
        "name": "Low Poly Stand Mixer Red",
        "description": "Stylish stand mixer model in bold red finish.",
        "category_id": "kitchen",
        "price_inr": 4299,
        "stock": 18,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1606859191214-25806e8e2427?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/low_poly_stand_mixer_red.glb",
        },
        "attributes": {
            "aesthetic_style": "Modern",
            "mood_feel": "Cosy & Inviting",
            "price_tier": "medium",
            "dominant_colors": ["red", "silver"],
            "materials": ["metal", "plastic"],
        },
    },
    {
        "sku": "KIT-106",
        "name": "Low Poly Toaster Red",
        "description": "Compact toaster model in red to match modern kitchen setups.",
        "category_id": "kitchen",
        "price_inr": 1999,
        "stock": 27,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1585238342024-78d387f4a707?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/low_poly_toaster_red.glb",
        },
        "attributes": {
            "aesthetic_style": "Modern",
            "mood_feel": "Sleek & Modern",
            "price_tier": "cheap",
            "dominant_colors": ["red", "black"],
            "materials": ["metal", "plastic"],
        },
    },
    {
        "sku": "CLS-201",
        "name": "Classroom Whiteboard",
        "description": "Essential teaching board model for classroom layouts.",
        "category_id": "classroom",
        "price_inr": 6999,
        "stock": 12,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/whiteboard_low-poly.glb",
        },
        "attributes": {
            "aesthetic_style": "Minimalist",
            "mood_feel": "Serene & Calm",
            "price_tier": "medium",
            "dominant_colors": ["white", "gray"],
            "materials": ["steel", "composite"],
        },
    },
    {
        "sku": "CLS-202",
        "name": "Classroom Computer Desk",
        "description": "Functional desk model for computer-based learning spaces.",
        "category_id": "classroom",
        "price_inr": 8499,
        "stock": 10,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/computer_desk.glb",
        },
        "attributes": {
            "aesthetic_style": "Modern",
            "mood_feel": "Sleek & Modern",
            "price_tier": "medium",
            "dominant_colors": ["brown", "black"],
            "materials": ["wood", "metal"],
        },
    },
    {
        "sku": "CLS-203",
        "name": "High School Desk",
        "description": "Student desk model designed for classroom seating rows.",
        "category_id": "classroom",
        "price_inr": 5999,
        "stock": 30,
        "is_active": True,
        "media": {
            "image_url": "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=1200",
            "glb_url": "https://radiant-sherbet-aa1f57.netlify.app/high_school_desk.glb",
        },
        "attributes": {
            "aesthetic_style": "Traditional",
            "mood_feel": "Cosy & Inviting",
            "price_tier": "cheap",
            "dominant_colors": ["wood", "gray"],
            "materials": ["wood", "steel"],
        },
    },
]
